spring:
  application:
    name: ts-assurance-service
  datasource:
    url: jdbc:mysql://${ASSURANCE_MYSQL_HOST:ts-assurance-mysql}:${ASSURANCE_MYSQL_PORT:3306}/${ASSURANCE_MYSQL_DATABASE:ts-assurance-mysql}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: ${ASSURANCE_MYSQL_USER:root}
    password: ${ASSURANCE_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    zipkin:
      base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 0.0

server:
  port: 18888

swagger:
  controllerPackage: assurance.controller