spring:
  application:
    name: ts-consign-price-service
  datasource:
    url: jdbc:mysql://${CONSIGN_PRICE_MYSQL_HOST:ts-consign-price-mysql}:${CONSIGN_PRICE_MYSQL_PORT:3306}/${CONSIGN_PRICE_MYSQL_DATABASE:ts-consign-price-mysql}?useSSL=false
    username: ${CONSIGN_PRICE_MYSQL_USER:root}
    password: ${CONSIGN_PRICE_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sleuth:
    otel:
      config:
        trace-id-ration-based: 1.0
  zipkin:
    base-url: http://zipkin:9411


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller