# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-order-service
  datasource:
    url: jdbc:mysql://${ORDER_MYSQL_HOST:ts-order-mysql}:${ORDER_MYSQL_PORT:3306}/${ORDER_MYSQL_DATABASE:ts-order-mysql}?useSSL=false
    username: ${ORDER_MYSQL_USER:root}
    password: ${ORDER_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

swagger:
  controllerPackage: order.controller