{
 "title": "Spring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_gc_pause_seconds_count) by (instance)"
    }
   ]
  },
  {
   "title": "Nonheap space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"}) by (instance) / (1024*1024)"
    }
   ]
  },
  {
   "title": "Max heap space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"}) by (instance) / (1024*1024)"
    }
   ]
  },
  {
   "title": "Heap space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (instance) / (1024*1024)\n"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"spring-boot-app\"}"
    }
   ]
  }
 ]
}