spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-price-service
  datasource:
    url: jdbc:mysql://${PRICE_MYSQL_HOST:ts-price-mysql}:${PRICE_MYSQL_PORT:3306}/${PRICE_MYSQL_DATABASE:ts-price-mysql}
    username: ${PRICE_MYSQL_USER:root}
    password: ${PRICE_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller