apiVersion: 1

datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Prometheus
    # <string, required> Sets the data source type.
    type: prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: a82ebd36-c63d-4b86-ba89-c639a6a4628a
    url: http://prometheus:9090
    jsonData:
      timeInterval: '5s'
    version: 1
    editable: true
