server:
  port: 18898

spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-seat-service
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    otel:
      config:
        trace-id-ration-based: 1.0

swagger:
  controllerPackage: seat.controller
