// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package fdse.microservice.entity;

public final class RouteOuterClass {
  private RouteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Route)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>repeated string stations = 2;</code>
     * @return A list containing the stations.
     */
    java.util.List<String>
        getStationsList();
    /**
     * <code>repeated string stations = 2;</code>
     * @return The count of stations.
     */
    int getStationsCount();
    /**
     * <code>repeated string stations = 2;</code>
     * @param index The index of the element to return.
     * @return The stations at the given index.
     */
    String getStations(int index);
    /**
     * <code>repeated string stations = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stations at the given index.
     */
    com.google.protobuf.ByteString
        getStationsBytes(int index);

    /**
     * <code>repeated int32 distances = 3;</code>
     * @return A list containing the distances.
     */
    java.util.List<Integer> getDistancesList();
    /**
     * <code>repeated int32 distances = 3;</code>
     * @return The count of distances.
     */
    int getDistancesCount();
    /**
     * <code>repeated int32 distances = 3;</code>
     * @param index The index of the element to return.
     * @return The distances at the given index.
     */
    int getDistances(int index);

    /**
     * <code>string startStation = 4;</code>
     * @return The startStation.
     */
    String getStartStation();
    /**
     * <code>string startStation = 4;</code>
     * @return The bytes for startStation.
     */
    com.google.protobuf.ByteString
        getStartStationBytes();

    /**
     * <code>string endStation = 5;</code>
     * @return The endStation.
     */
    String getEndStation();
    /**
     * <code>string endStation = 5;</code>
     * @return The bytes for endStation.
     */
    com.google.protobuf.ByteString
        getEndStationBytes();
  }
  /**
   * Protobuf type {@code proto.Route}
   */
  public static final class Route extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Route)
      RouteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Route.newBuilder() to construct.
    private Route(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Route() {
      id_ = "";
      stations_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      distances_ = emptyIntList();
      startStation_ = "";
      endStation_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Route();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteOuterClass.internal_static_proto_Route_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteOuterClass.internal_static_proto_Route_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Route.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATIONS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList stations_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string stations = 2;</code>
     * @return A list containing the stations.
     */
    public com.google.protobuf.ProtocolStringList
        getStationsList() {
      return stations_;
    }
    /**
     * <code>repeated string stations = 2;</code>
     * @return The count of stations.
     */
    public int getStationsCount() {
      return stations_.size();
    }
    /**
     * <code>repeated string stations = 2;</code>
     * @param index The index of the element to return.
     * @return The stations at the given index.
     */
    public String getStations(int index) {
      return stations_.get(index);
    }
    /**
     * <code>repeated string stations = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stations at the given index.
     */
    public com.google.protobuf.ByteString
        getStationsBytes(int index) {
      return stations_.getByteString(index);
    }

    public static final int DISTANCES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList distances_ =
        emptyIntList();
    /**
     * <code>repeated int32 distances = 3;</code>
     * @return A list containing the distances.
     */
    @Override
    public java.util.List<Integer>
        getDistancesList() {
      return distances_;
    }
    /**
     * <code>repeated int32 distances = 3;</code>
     * @return The count of distances.
     */
    public int getDistancesCount() {
      return distances_.size();
    }
    /**
     * <code>repeated int32 distances = 3;</code>
     * @param index The index of the element to return.
     * @return The distances at the given index.
     */
    public int getDistances(int index) {
      return distances_.getInt(index);
    }
    private int distancesMemoizedSerializedSize = -1;

    public static final int STARTSTATION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object startStation_ = "";
    /**
     * <code>string startStation = 4;</code>
     * @return The startStation.
     */
    @Override
    public String getStartStation() {
      Object ref = startStation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        startStation_ = s;
        return s;
      }
    }
    /**
     * <code>string startStation = 4;</code>
     * @return The bytes for startStation.
     */
    @Override
    public com.google.protobuf.ByteString
        getStartStationBytes() {
      Object ref = startStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDSTATION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object endStation_ = "";
    /**
     * <code>string endStation = 5;</code>
     * @return The endStation.
     */
    @Override
    public String getEndStation() {
      Object ref = endStation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        endStation_ = s;
        return s;
      }
    }
    /**
     * <code>string endStation = 5;</code>
     * @return The bytes for endStation.
     */
    @Override
    public com.google.protobuf.ByteString
        getEndStationBytes() {
      Object ref = endStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      for (int i = 0; i < stations_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stations_.getRaw(i));
      }
      if (getDistancesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(distancesMemoizedSerializedSize);
      }
      for (int i = 0; i < distances_.size(); i++) {
        output.writeInt32NoTag(distances_.getInt(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startStation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, startStation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endStation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, endStation_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stations_.size(); i++) {
          dataSize += computeStringSizeNoTag(stations_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStationsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < distances_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(distances_.getInt(i));
        }
        size += dataSize;
        if (!getDistancesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        distancesMemoizedSerializedSize = dataSize;
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startStation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, startStation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endStation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, endStation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Route)) {
        return super.equals(obj);
      }
      Route other = (Route) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getStationsList()
          .equals(other.getStationsList())) return false;
      if (!getDistancesList()
          .equals(other.getDistancesList())) return false;
      if (!getStartStation()
          .equals(other.getStartStation())) return false;
      if (!getEndStation()
          .equals(other.getEndStation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getStationsCount() > 0) {
        hash = (37 * hash) + STATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getStationsList().hashCode();
      }
      if (getDistancesCount() > 0) {
        hash = (37 * hash) + DISTANCES_FIELD_NUMBER;
        hash = (53 * hash) + getDistancesList().hashCode();
      }
      hash = (37 * hash) + STARTSTATION_FIELD_NUMBER;
      hash = (53 * hash) + getStartStation().hashCode();
      hash = (37 * hash) + ENDSTATION_FIELD_NUMBER;
      hash = (53 * hash) + getEndStation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Route parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Route parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Route parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Route parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Route parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Route parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Route prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Route}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Route)
        RouteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RouteOuterClass.internal_static_proto_Route_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RouteOuterClass.internal_static_proto_Route_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Route.class, Builder.class);
      }

      // Construct using route.entity.RouteOuterClass.Route.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        stations_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        distances_ = emptyIntList();
        startStation_ = "";
        endStation_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RouteOuterClass.internal_static_proto_Route_descriptor;
      }

      @Override
      public Route getDefaultInstanceForType() {
        return Route.getDefaultInstance();
      }

      @Override
      public Route build() {
        Route result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Route buildPartial() {
        Route result = new Route(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Route result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          stations_.makeImmutable();
          result.stations_ = stations_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          distances_.makeImmutable();
          result.distances_ = distances_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.startStation_ = startStation_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.endStation_ = endStation_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Route) {
          return mergeFrom((Route)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Route other) {
        if (other == Route.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.stations_.isEmpty()) {
          if (stations_.isEmpty()) {
            stations_ = other.stations_;
            bitField0_ |= 0x00000002;
          } else {
            ensureStationsIsMutable();
            stations_.addAll(other.stations_);
          }
          onChanged();
        }
        if (!other.distances_.isEmpty()) {
          if (distances_.isEmpty()) {
            distances_ = other.distances_;
            distances_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureDistancesIsMutable();
            distances_.addAll(other.distances_);
          }
          onChanged();
        }
        if (!other.getStartStation().isEmpty()) {
          startStation_ = other.startStation_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getEndStation().isEmpty()) {
          endStation_ = other.endStation_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                String s = input.readStringRequireUtf8();
                ensureStationsIsMutable();
                stations_.add(s);
                break;
              } // case 18
              case 24: {
                int v = input.readInt32();
                ensureDistancesIsMutable();
                distances_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureDistancesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  distances_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 34: {
                startStation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                endStation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList stations_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureStationsIsMutable() {
        if (!stations_.isModifiable()) {
          stations_ = new com.google.protobuf.LazyStringArrayList(stations_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @return A list containing the stations.
       */
      public com.google.protobuf.ProtocolStringList
          getStationsList() {
        stations_.makeImmutable();
        return stations_;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @return The count of stations.
       */
      public int getStationsCount() {
        return stations_.size();
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param index The index of the element to return.
       * @return The stations at the given index.
       */
      public String getStations(int index) {
        return stations_.get(index);
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the stations at the given index.
       */
      public com.google.protobuf.ByteString
          getStationsBytes(int index) {
        return stations_.getByteString(index);
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param index The index to set the value at.
       * @param value The stations to set.
       * @return This builder for chaining.
       */
      public Builder setStations(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStationsIsMutable();
        stations_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param value The stations to add.
       * @return This builder for chaining.
       */
      public Builder addStations(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStationsIsMutable();
        stations_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param values The stations to add.
       * @return This builder for chaining.
       */
      public Builder addAllStations(
          Iterable<String> values) {
        ensureStationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stations_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStations() {
        stations_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stations = 2;</code>
       * @param value The bytes of the stations to add.
       * @return This builder for chaining.
       */
      public Builder addStationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureStationsIsMutable();
        stations_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList distances_ = emptyIntList();
      private void ensureDistancesIsMutable() {
        if (!distances_.isModifiable()) {
          distances_ = makeMutableCopy(distances_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @return A list containing the distances.
       */
      public java.util.List<Integer>
          getDistancesList() {
        distances_.makeImmutable();
        return distances_;
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @return The count of distances.
       */
      public int getDistancesCount() {
        return distances_.size();
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @param index The index of the element to return.
       * @return The distances at the given index.
       */
      public int getDistances(int index) {
        return distances_.getInt(index);
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @param index The index to set the value at.
       * @param value The distances to set.
       * @return This builder for chaining.
       */
      public Builder setDistances(
          int index, int value) {

        ensureDistancesIsMutable();
        distances_.setInt(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @param value The distances to add.
       * @return This builder for chaining.
       */
      public Builder addDistances(int value) {

        ensureDistancesIsMutable();
        distances_.addInt(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @param values The distances to add.
       * @return This builder for chaining.
       */
      public Builder addAllDistances(
          Iterable<? extends Integer> values) {
        ensureDistancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, distances_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistances() {
        distances_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private Object startStation_ = "";
      /**
       * <code>string startStation = 4;</code>
       * @return The startStation.
       */
      public String getStartStation() {
        Object ref = startStation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          startStation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string startStation = 4;</code>
       * @return The bytes for startStation.
       */
      public com.google.protobuf.ByteString
          getStartStationBytes() {
        Object ref = startStation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          startStation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startStation = 4;</code>
       * @param value The startStation to set.
       * @return This builder for chaining.
       */
      public Builder setStartStation(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        startStation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string startStation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartStation() {
        startStation_ = getDefaultInstance().getStartStation();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string startStation = 4;</code>
       * @param value The bytes for startStation to set.
       * @return This builder for chaining.
       */
      public Builder setStartStationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        startStation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object endStation_ = "";
      /**
       * <code>string endStation = 5;</code>
       * @return The endStation.
       */
      public String getEndStation() {
        Object ref = endStation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          endStation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string endStation = 5;</code>
       * @return The bytes for endStation.
       */
      public com.google.protobuf.ByteString
          getEndStationBytes() {
        Object ref = endStation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endStation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endStation = 5;</code>
       * @param value The endStation to set.
       * @return This builder for chaining.
       */
      public Builder setEndStation(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        endStation_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string endStation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndStation() {
        endStation_ = getDefaultInstance().getEndStation();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string endStation = 5;</code>
       * @param value The bytes for endStation to set.
       * @return This builder for chaining.
       */
      public Builder setEndStationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        endStation_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Route)
    }

    // @@protoc_insertion_point(class_scope:proto.Route)
    private static final Route DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Route();
    }

    public static Route getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Route>
        PARSER = new com.google.protobuf.AbstractParser<Route>() {
      @Override
      public Route parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Route> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Route> getParserForType() {
      return PARSER;
    }

    @Override
    public Route getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    java.util.List<Route>
        getRoutesList();
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    Route getRoutes(int index);
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    int getRoutesCount();
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    java.util.List<? extends RouteOrBuilder>
        getRoutesOrBuilderList();
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    RouteOrBuilder getRoutesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      msg_ = "";
      routes_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteOuterClass.internal_static_proto_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteOuterClass.internal_static_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @Override
    public int getStatus() {
      return status_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object msg_ = "";
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @Override
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<Route> routes_;
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    @Override
    public java.util.List<Route> getRoutesList() {
      return routes_;
    }
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    @Override
    public java.util.List<? extends RouteOrBuilder>
        getRoutesOrBuilderList() {
      return routes_;
    }
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    @Override
    public int getRoutesCount() {
      return routes_.size();
    }
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    @Override
    public Route getRoutes(int index) {
      return routes_.get(index);
    }
    /**
     * <code>repeated .proto.Route routes = 3;</code>
     */
    @Override
    public RouteOrBuilder getRoutesOrBuilder(
        int index) {
      return routes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      for (int i = 0; i < routes_.size(); i++) {
        output.writeMessage(3, routes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      for (int i = 0; i < routes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, routes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response)) {
        return super.equals(obj);
      }
      Response other = (Response) obj;

      if (getStatus()
          != other.getStatus()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!getRoutesList()
          .equals(other.getRoutesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (getRoutesCount() > 0) {
        hash = (37 * hash) + ROUTES_FIELD_NUMBER;
        hash = (53 * hash) + getRoutesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Response)
        ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RouteOuterClass.internal_static_proto_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RouteOuterClass.internal_static_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      // Construct using route.entity.RouteOuterClass.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        msg_ = "";
        if (routesBuilder_ == null) {
          routes_ = java.util.Collections.emptyList();
        } else {
          routes_ = null;
          routesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RouteOuterClass.internal_static_proto_Response_descriptor;
      }

      @Override
      public Response getDefaultInstanceForType() {
        return Response.getDefaultInstance();
      }

      @Override
      public Response build() {
        Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Response buildPartial() {
        Response result = new Response(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Response result) {
        if (routesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            routes_ = java.util.Collections.unmodifiableList(routes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.routes_ = routes_;
        } else {
          result.routes_ = routesBuilder_.build();
        }
      }

      private void buildPartial0(Response result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msg_ = msg_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response) {
          return mergeFrom((Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response other) {
        if (other == Response.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (routesBuilder_ == null) {
          if (!other.routes_.isEmpty()) {
            if (routes_.isEmpty()) {
              routes_ = other.routes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRoutesIsMutable();
              routes_.addAll(other.routes_);
            }
            onChanged();
          }
        } else {
          if (!other.routes_.isEmpty()) {
            if (routesBuilder_.isEmpty()) {
              routesBuilder_.dispose();
              routesBuilder_ = null;
              routes_ = other.routes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              routesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoutesFieldBuilder() : null;
            } else {
              routesBuilder_.addAllMessages(other.routes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                msg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                Route m =
                    input.readMessage(
                        Route.parser(),
                        extensionRegistry);
                if (routesBuilder_ == null) {
                  ensureRoutesIsMutable();
                  routes_.add(m);
                } else {
                  routesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       * @return The status.
       */
      @Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        msg_ = getDefaultInstance().getMsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<Route> routes_ =
        java.util.Collections.emptyList();
      private void ensureRoutesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          routes_ = new java.util.ArrayList<Route>(routes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Route, Route.Builder, RouteOrBuilder> routesBuilder_;

      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public java.util.List<Route> getRoutesList() {
        if (routesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routes_);
        } else {
          return routesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public int getRoutesCount() {
        if (routesBuilder_ == null) {
          return routes_.size();
        } else {
          return routesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Route getRoutes(int index) {
        if (routesBuilder_ == null) {
          return routes_.get(index);
        } else {
          return routesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder setRoutes(
          int index, Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.set(index, value);
          onChanged();
        } else {
          routesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder setRoutes(
          int index, Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.set(index, builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder addRoutes(Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.add(value);
          onChanged();
        } else {
          routesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder addRoutes(
          int index, Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.add(index, value);
          onChanged();
        } else {
          routesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder addRoutes(
          Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.add(builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder addRoutes(
          int index, Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.add(index, builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder addAllRoutes(
          Iterable<? extends Route> values) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routes_);
          onChanged();
        } else {
          routesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder clearRoutes() {
        if (routesBuilder_ == null) {
          routes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          routesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Builder removeRoutes(int index) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.remove(index);
          onChanged();
        } else {
          routesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Route.Builder getRoutesBuilder(
          int index) {
        return getRoutesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public RouteOrBuilder getRoutesOrBuilder(
          int index) {
        if (routesBuilder_ == null) {
          return routes_.get(index);  } else {
          return routesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public java.util.List<? extends RouteOrBuilder>
           getRoutesOrBuilderList() {
        if (routesBuilder_ != null) {
          return routesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routes_);
        }
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Route.Builder addRoutesBuilder() {
        return getRoutesFieldBuilder().addBuilder(
            Route.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public Route.Builder addRoutesBuilder(
          int index) {
        return getRoutesFieldBuilder().addBuilder(
            index, Route.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Route routes = 3;</code>
       */
      public java.util.List<Route.Builder>
           getRoutesBuilderList() {
        return getRoutesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Route, Route.Builder, RouteOrBuilder>
          getRoutesFieldBuilder() {
        if (routesBuilder_ == null) {
          routesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Route, Route.Builder, RouteOrBuilder>(
                  routes_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          routes_ = null;
        }
        return routesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Response)
    }

    // @@protoc_insertion_point(class_scope:proto.Response)
    private static final Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @Override
    public Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Route_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Route_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013route.proto\022\005proto\"b\n\005Route\022\n\n\002id\030\001 \001(" +
      "\t\022\020\n\010stations\030\002 \003(\t\022\021\n\tdistances\030\003 \003(\005\022\024" +
      "\n\014startStation\030\004 \001(\t\022\022\n\nendStation\030\005 \001(\t" +
      "\"E\n\010Response\022\016\n\006status\030\001 \001(\005\022\013\n\003msg\030\002 \001(" +
      "\t\022\034\n\006routes\030\003 \003(\0132\014.proto.Routeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Route_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Route_descriptor,
        new String[] { "Id", "Stations", "Distances", "StartStation", "EndStation", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new String[] { "Status", "Msg", "Routes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
