# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ts-travel-service
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:mysql://${TRAVEL_MYSQL_HOST:ts-travel-mysql}:${TRAVEL_MYSQL_PORT:3306}/${TRAVEL_MYSQL_DATABASE:ts-travel-mysql}?useSSL=false
    username: ${TRAVEL_MYSQL_USER:root}
    password: ${TRAVEL_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  sleuth:
    otel:
      config:
        trace-id-ration-based: 1.0

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: travel.controller

train-service:
  url: http://${TRAIN_SERVICE_HOST:localhost}:${TRAIN_SERVICE_PORT:14567}

order-service:
  url: http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:12031}

route-service:
  url: http://${ROUTE_SERVICE_HOST:localhost}:${ROUTE_SERVICE_PORT:11178}

basic-service:
  url: http://${BASIC_SERVICE_HOST:localhost}:${BASIC_SERVICE_PORT:15680}

seat-service:
  url: http://${SEAT_SERVICE_HOST:localhost}:${SEAT_SERVICE_PORT:18898}