version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

  ts-route-service:
    image: thesis/ts-route-service:0.2.0
    restart: "no"
    ports:
      - 11178:11178
    networks:
      - my-network

  ts-route-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-route-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    networks:
      - my-network

  ts-station-service:
    image: thesis/ts-station-service:0.2.0
    restart: "no"
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-station-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-station-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    networks:
      - my-network

  ts-travel-service:
    image: thesis/ts-travel-service:0.2.0
    restart: "no"
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-travel-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    networks:
      - my-network

  ts-basic-service:
    image: thesis/ts-basic-service:0.2.0
    restart: "no"
    ports:
      - 15680:15680
    networks:
      - my-network

  ts-seat-service:
    build: ts-seat-service
    image: thesis/ts-seat-service:0.2.0
    restart: always
    ports:
      - 18898:18898
    networks:
      - my-network

  ts-config-service:
    build: ts-config-service
    image: thesis/ts-config-service:0.2.0
    restart: always
    ports:
      - 15679:15679
    networks:
      - my-network

  ts-config-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-config-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3309:3306'
    networks:
      - my-network

  ts-train-service:
    build: ts-train-service
    image: thesis/ts-train-service:0.2.0
    restart: always
    ports:
      - 14567:14567
    networks:
      - my-network

  ts-train-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-train-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3310:3306'
    networks:
      - my-network

  ts-price-service:
    build: ts-price-service
    image: thesis/ts-price-service:0.2.0
    restart: always
    ports:
      - 16579:16579
    networks:
      - my-network

  ts-price-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-price-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3311:3306'
    networks:
      - my-network

  ts-order-service:
    build: ts-order-service
    image: thesis/ts-order-service:0.2.0
    restart: always
    ports:
      - 12031:12031
    networks:
      - my-network

  ts-order-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-order-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3312:3306'
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge
