version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

  ts-route-service:
    image: thesis/ts-route-service:0.2.0
    restart: "no"
    ports:
      - 11178:11178
    networks:
      - my-network

  ts-route-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-route-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    networks:
        - my-network

  ts-station-service:
    image: thesis/ts-station-service:0.2.0
    restart: "no"
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-travel-service:
    image: thesis/ts-travel-service:0.2.0
    restart: "no"
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-travel-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    networks:
      - my-network

  ts-basic-service:
    image: thesis/ts-basic-service:0.2.0
    restart: "no"
    ports:
      - 15680:15680
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge
