version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - JAVA_OPTS=-Xmx2g
    networks:
      - my-network

  ts-consign-service:
    image: thesis/ts-consign-service:0.3.0
    restart: "no"
    ports:
      - 16111:16111
    networks:
      - my-network

  ts-consign-price-service:
    image: thesis/ts-consign-price-service:0.3.0
    restart: "no"
    ports:
      - 16110:16110
    networks:
      - my-network

  ts-consign-price-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ts-consign-price-mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge
