spring:
  application:
    name: ts-consign-service
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    otel:
      config:

# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller

